### ISSUE TITLE
ImportError: cannot import name 'apply_dtg_prompt' from 'kgen.formatter'

### ISSUE THREAD

**Issue by kirintea** [KohakuBlueleaf/KGen#4]
ImportError: cannot import name 'apply_dtg_prompt' from 'kgen.formatter'
'tag_gen' not found in kgen.generate

**Comment by KohakuBlueleaf** [comment]
[1058e77](https://github.com/KohakuBlueleaf/KGen/commit/1058e77ecb7254f756412cde836de602c39d8a07)
